--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.34.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 1/31/2018 11:28:19 AM
-- Server version: 5.7.18-log
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE healthbot;

--
-- Definition for table tbl_section_type
--
DROP TABLE IF EXISTS tbl_section_type;
CREATE TABLE tbl_section_type (
  section_type_id INT(11) NOT NULL AUTO_INCREMENT,
  section_type_image BLOB DEFAULT NULL,
  section_type_video LONGBLOB DEFAULT NULL,
  section_type_text TEXT DEFAULT NULL,
  PRIMARY KEY (section_type_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table tbl_user_type
--
DROP TABLE IF EXISTS tbl_user_type;
CREATE TABLE tbl_user_type (
  user_type_id INT(11) NOT NULL AUTO_INCREMENT,
  user_type_name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (user_type_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table tbl_users
--
DROP TABLE IF EXISTS tbl_users;
CREATE TABLE tbl_users (
  user_id INT(11) NOT NULL AUTO_INCREMENT,
  user_name VARCHAR(255) DEFAULT NULL,
  gender VARCHAR(20) DEFAULT NULL,
  goals TEXT DEFAULT NULL,
  user_type_id INT(11) NOT NULL,
  PRIMARY KEY (user_id),
  CONSTRAINT FK_tbl_users_user_type_id FOREIGN KEY (user_type_id)
    REFERENCES tbl_user_type(user_type_id) ON DELETE NO ACTION ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = 'added tbl_user_type foreign key to tbl_users '
ROW_FORMAT = DYNAMIC;

--
-- Definition for table tbl_study
--
DROP TABLE IF EXISTS tbl_study;
CREATE TABLE tbl_study (
  study_id INT(11) NOT NULL AUTO_INCREMENT,
  study_desc VARCHAR(255) DEFAULT NULL,
  start_date DATETIME DEFAULT NULL,
  end_date DATETIME DEFAULT NULL,
  user_id INT(11) NOT NULL,
  PRIMARY KEY (study_id),
  CONSTRAINT FK_tbl_study_user_id FOREIGN KEY (user_id)
    REFERENCES tbl_users(user_id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table tbl_modules
--
DROP TABLE IF EXISTS tbl_modules;
CREATE TABLE tbl_modules (
  module_id INT(11) NOT NULL AUTO_INCREMENT,
  module_desc TEXT DEFAULT NULL,
  module_title VARCHAR(255) DEFAULT NULL,
  module_video_url VARCHAR(255) DEFAULT NULL,
  goals TEXT DEFAULT NULL,
  start_time DATETIME DEFAULT NULL,
  end_time DATETIME DEFAULT NULL,
  user_id INT(11) DEFAULT NULL,
  study_id INT(11) DEFAULT NULL,
  PRIMARY KEY (module_id),
  CONSTRAINT FK_tbl_modules_study_id FOREIGN KEY (study_id)
    REFERENCES tbl_study(study_id) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT FK_tbl_modules_user_id FOREIGN KEY (user_id)
    REFERENCES tbl_users(user_id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table tbl_question
--
DROP TABLE IF EXISTS tbl_question;
CREATE TABLE tbl_question (
  question_id INT(11) NOT NULL AUTO_INCREMENT,
  Question TEXT DEFAULT NULL,
  user_id INT(11) DEFAULT NULL,
  module_id INT(11) DEFAULT NULL,
  PRIMARY KEY (question_id),
  CONSTRAINT FK_tbl_question_module_id FOREIGN KEY (module_id)
    REFERENCES tbl_modules(module_id) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT FK_tbl_question_user_id FOREIGN KEY (user_id)
    REFERENCES tbl_users(user_id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table tbl_section
--
DROP TABLE IF EXISTS tbl_section;
CREATE TABLE tbl_section (
  section_id INT(11) NOT NULL AUTO_INCREMENT,
  section_name VARCHAR(255) DEFAULT NULL,
  section_order INT(11) DEFAULT NULL,
  section_description TEXT DEFAULT NULL,
  section_type_id INT(11) DEFAULT NULL,
  module_id INT(11) NOT NULL,
  PRIMARY KEY (section_id),
  CONSTRAINT FK_tble_section_module_id FOREIGN KEY (module_id)
    REFERENCES tbl_modules(module_id) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT FK_tble_section_section_type_i FOREIGN KEY (section_type_id)
    REFERENCES tbl_section_type(section_type_id) ON DELETE NO ACTION ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table tbl_user_modules
--
DROP TABLE IF EXISTS tbl_user_modules;
CREATE TABLE tbl_user_modules (
  user_module_id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) DEFAULT NULL,
  module_id INT(11) DEFAULT NULL,
  start_date DATETIME DEFAULT NULL,
  end_date DATETIME DEFAULT NULL,
  PRIMARY KEY (user_module_id),
  CONSTRAINT FK_tbl_user_modules_module_id FOREIGN KEY (module_id)
    REFERENCES tbl_modules(module_id) ON DELETE NO ACTION ON UPDATE RESTRICT,
  CONSTRAINT FK_tbl_user_modules_user_id FOREIGN KEY (user_id)
    REFERENCES tbl_users(user_id) ON DELETE NO ACTION ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table tbl_answers
--
DROP TABLE IF EXISTS tbl_answers;
CREATE TABLE tbl_answers (
  answer_id INT(11) NOT NULL AUTO_INCREMENT,
  answer TEXT DEFAULT NULL,
  user_id INT(11) NOT NULL,
  module_id INT(11) NOT NULL,
  question_id INT(11) NOT NULL,
  PRIMARY KEY (answer_id),
  CONSTRAINT FK_tbl_answers_module_id FOREIGN KEY (module_id)
    REFERENCES tbl_modules(module_id) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT FK_tbl_answers_question_id FOREIGN KEY (question_id)
    REFERENCES tbl_question(question_id) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT FK_tbl_answers_user_id FOREIGN KEY (user_id)
    REFERENCES tbl_users(user_id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table tbl_user_module_survey
--
DROP TABLE IF EXISTS tbl_user_module_survey;
CREATE TABLE tbl_user_module_survey (
  user_module_survey_id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) DEFAULT NULL,
  module_id INT(11) DEFAULT NULL,
  question_id INT(11) DEFAULT NULL,
  answer_id INT(11) DEFAULT NULL,
  PRIMARY KEY (user_module_survey_id),
  CONSTRAINT FK_tbl_user_module_survey_answ FOREIGN KEY (answer_id)
    REFERENCES tbl_answers(answer_id) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT FK_tbl_user_module_survey_modu FOREIGN KEY (module_id)
    REFERENCES tbl_modules(module_id) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT FK_tbl_user_module_survey_ques FOREIGN KEY (question_id)
    REFERENCES tbl_question(question_id) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT FK_tbl_user_module_survey_user FOREIGN KEY (user_id)
    REFERENCES tbl_users(user_id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table tbl_section_type
--

-- Table healthbot.tbl_section_type does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_user_type
--
INSERT INTO tbl_user_type VALUES
(1, 'Reserchers'),
(2, 'Practitioners');

-- 
-- Dumping data for table tbl_users
--
INSERT INTO tbl_users VALUES
(1, 'Chathu', 'Female', 'Losing Weight', 1),
(2, 'Aamer', 'Male', 'Fitness', 2),
(3, 'caro', 'FEMALE', 'JHCDCD', 2),
(4, 'nikhi', 'FEMALE', 'CCDC', 2),
(5, 'Sandesh', 'MALE', 'SCJIECE', 1);

-- 
-- Dumping data for table tbl_study
--
INSERT INTO tbl_study VALUES
(1, 'Fitness', '2018-01-14 23:02:15', '2018-01-14 23:02:17', 1),
(2, 'rgrgr', '2018-01-14 00:00:00', '2018-01-14 00:00:00', 1),
(3, 'cdffv', '2018-01-17 00:00:00', '2018-01-17 00:00:00', 1);

-- 
-- Dumping data for table tbl_modules
--
INSERT INTO tbl_modules VALUES
(1, 'fitn', 'dffd', 'fdfdf', 'fdfdf', '2018-01-17 10:47:47', '2018-01-15 10:47:50', 1, 1);

-- 
-- Dumping data for table tbl_question
--

-- Table healthbot.tbl_question does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_section
--

-- Table healthbot.tbl_section does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_user_modules
--

-- Table healthbot.tbl_user_modules does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_answers
--

-- Table healthbot.tbl_answers does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_user_module_survey
--

-- Table healthbot.tbl_user_module_survey does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;