package com.heathbot.beans;
// Generated Jan 18, 2018 5:18:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblModules generated by hbm2java
 */
@Entity
@Table(name = "tbl_modules", catalog = "healthbot")
public class TblModules implements java.io.Serializable {

	private Integer moduleId;
	private TblUsers tblUsers;
	private TblStudy tblStudy;
	private String moduleDesc;
	private String moduleTitle;
	private String moduleVideoUrl;
	private String goals;
	private Date startTime;
	private Date endTime;
	private Set<TblUserModuleSurvey> tblUserModuleSurveys = new HashSet<TblUserModuleSurvey>(0);
	private Set<TblSection> tblSections = new HashSet<TblSection>(0);
	private Set<TblUserModules> tblUserModuleses = new HashSet<TblUserModules>(0);
	private Set<TblQuestion> tblQuestions = new HashSet<TblQuestion>(0);
	private Set<TblAnswers> tblAnswerses = new HashSet<TblAnswers>(0);

	public TblModules() {
	}

	public TblModules(Integer moduleId, TblUsers tblUsers, TblStudy tblStudy,
			String moduleDesc, String moduleTitle, String moduleVideoUrl,
			String goals, Date startTime, Date endTime,
			Set<TblUserModuleSurvey> tblUserModuleSurveys,
			Set<TblSection> tblSections, Set<TblUserModules> tblUserModuleses,
			Set<TblQuestion> tblQuestions, Set<TblAnswers> tblAnswerses) {
		super();
		this.moduleId = moduleId;
		this.tblUsers = tblUsers;
		this.tblStudy = tblStudy;
		this.moduleDesc = moduleDesc;
		this.moduleTitle = moduleTitle;
		this.moduleVideoUrl = moduleVideoUrl;
		this.goals = goals;
		this.startTime = startTime;
		this.endTime = endTime;
		this.tblUserModuleSurveys = tblUserModuleSurveys;
		this.tblSections = tblSections;
		this.tblUserModuleses = tblUserModuleses;
		this.tblQuestions = tblQuestions;
		this.tblAnswerses = tblAnswerses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "module_id", unique = true, nullable = false)
	public Integer getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public TblUsers getTblUsers() {
		return this.tblUsers;
	}

	public void setTblUsers(TblUsers tblUsers) {
		this.tblUsers = tblUsers;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = TblStudy.class)
	@JoinColumn(name = "study_id")
	public TblStudy getTblStudy() {
		return this.tblStudy;
	}

	public void setTblStudy(TblStudy tblStudy) {
		this.tblStudy = tblStudy;
	}

	@Column(name = "module_desc", length = 65535)
	public String getModuleDesc() {
		return this.moduleDesc;
	}

	public void setModuleDesc(String moduleDesc) {
		this.moduleDesc = moduleDesc;
	}

	@Column(name = "module_title")
	public String getModuleTitle() {
		return this.moduleTitle;
	}

	public void setModuleTitle(String moduleTitle) {
		this.moduleTitle = moduleTitle;
	}

	@Column(name = "module_video_url")
	public String getModuleVideoUrl() {
		return this.moduleVideoUrl;
	}

	public void setModuleVideoUrl(String moduleVideoUrl) {
		this.moduleVideoUrl = moduleVideoUrl;
	}

	@Column(name = "goals", length = 65535)
	public String getGoals() {
		return this.goals;
	}

	public void setGoals(String goals) {
		this.goals = goals;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time", length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblModules")
	public Set<TblUserModuleSurvey> getTblUserModuleSurveys() {
		return this.tblUserModuleSurveys;
	}

	public void setTblUserModuleSurveys(
			Set<TblUserModuleSurvey> tblUserModuleSurveys) {
		this.tblUserModuleSurveys = tblUserModuleSurveys;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblModules")
	public Set<TblSection> getTblSections() {
		return this.tblSections;
	}

	public void setTblSections(Set<TblSection> tblSections) {
		this.tblSections = tblSections;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblModules")
	public Set<TblUserModules> getTblUserModuleses() {
		return this.tblUserModuleses;
	}

	public void setTblUserModuleses(Set<TblUserModules> tblUserModuleses) {
		this.tblUserModuleses = tblUserModuleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblModules")
	public Set<TblQuestion> getTblQuestions() {
		return this.tblQuestions;
	}

	public void setTblQuestions(Set<TblQuestion> tblQuestions) {
		this.tblQuestions = tblQuestions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblModules")
	public Set<TblAnswers> getTblAnswerses() {
		return this.tblAnswerses;
	}

	public void setTblAnswerses(Set<TblAnswers> tblAnswerses) {
		this.tblAnswerses = tblAnswerses;
	}

}
