package com.heathbot.beans;
// Generated Jan 18, 2018 5:18:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblStudy generated by hbm2java
 */
@Entity
@Table(name = "tbl_study", catalog = "healthbot")
public class TblStudy implements java.io.Serializable {

	private Integer studyId;
	private TblUsers tblUsers;
	private String studyDesc;
	private Date startDate;
	private Date endDate;
	private Set<TblModules> tblModuleses = new HashSet<TblModules>(0);

	public TblStudy() {
	}

	public TblStudy(TblUsers tblUsers) {
		this.tblUsers = tblUsers;
	}

	public TblStudy(Integer studyId, TblUsers tblUsers, String studyDesc,
			Date startDate, Date endDate, Set<TblModules> tblModuleses) {
		super();
		this.studyId = studyId;
		this.tblUsers = tblUsers;
		this.studyDesc = studyDesc;
		this.startDate = startDate;
		this.endDate = endDate;
		this.tblModuleses = tblModuleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "study_id", unique = true, nullable = false)
	public Integer getStudyId() {
		return this.studyId;
	}

	public void setStudyId(Integer studyId) {
		this.studyId = studyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public TblUsers getTblUsers() {
		return this.tblUsers;
	}

	public void setTblUsers(TblUsers tblUsers) {
		this.tblUsers = tblUsers;
	}

	@Column(name = "study_desc")
	public String getStudyDesc() {
		return this.studyDesc;
	}

	public void setStudyDesc(String studyDesc) {
		this.studyDesc = studyDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblStudy")
	public Set<TblModules> getTblModuleses() {
		return this.tblModuleses;
	}

	public void setTblModuleses(Set<TblModules> tblModuleses) {
		this.tblModuleses = tblModuleses;
	}

	@Override
	public String toString() {
		return "TblStudy [studyId=" + studyId + ", tblUsers=" + tblUsers
				+ ", studyDesc=" + studyDesc + ", startDate=" + startDate
				+ ", endDate=" + endDate + ", tblModuleses=" + tblModuleses
				+ "]";
	}

	
	
}
