package com.heathbot.beans;
// Generated Jan 18, 2018 5:18:56 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblSection generated by hbm2java
 */
@Entity
@Table(name = "tbl_section", catalog = "healthbot")
public class TblSection implements java.io.Serializable {

	private Integer sectionId;
	private TblModules tblModules;
	private TblSectionType tblSectionType;
	private String sectionName;
	private Integer sectionOrder;
	private String sectionDescription;

	public TblSection() {
	}

	public TblSection(TblModules tblModules) {
		this.tblModules = tblModules;
	}

	public TblSection(TblModules tblModules, TblSectionType tblSectionType,
			String sectionName, Integer sectionOrder, String sectionDescription) {
		this.tblModules = tblModules;
		this.tblSectionType = tblSectionType;
		this.sectionName = sectionName;
		this.sectionOrder = sectionOrder;
		this.sectionDescription = sectionDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "section_id", unique = true, nullable = false)
	public Integer getSectionId() {
		return this.sectionId;
	}

	public void setSectionId(Integer sectionId) {
		this.sectionId = sectionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module_id", nullable = false)
	public TblModules getTblModules() {
		return this.tblModules;
	}

	public void setTblModules(TblModules tblModules) {
		this.tblModules = tblModules;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "section_type_id")
	public TblSectionType getTblSectionType() {
		return this.tblSectionType;
	}

	public void setTblSectionType(TblSectionType tblSectionType) {
		this.tblSectionType = tblSectionType;
	}

	@Column(name = "section_name")
	public String getSectionName() {
		return this.sectionName;
	}

	public void setSectionName(String sectionName) {
		this.sectionName = sectionName;
	}

	@Column(name = "section_order")
	public Integer getSectionOrder() {
		return this.sectionOrder;
	}

	public void setSectionOrder(Integer sectionOrder) {
		this.sectionOrder = sectionOrder;
	}

	@Column(name = "section_description", length = 65535)
	public String getSectionDescription() {
		return this.sectionDescription;
	}

	public void setSectionDescription(String sectionDescription) {
		this.sectionDescription = sectionDescription;
	}

}
