package com.heathbot.beans;
// Generated Jan 18, 2018 5:18:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblUserModules generated by hbm2java
 */
@Entity
@Table(name = "tbl_user_modules", catalog = "healthbot")
public class TblUserModules implements java.io.Serializable {

	private Integer userModuleId;
	private TblUsers tblUsers;
	private TblModules tblModules;
	private Date startDate;
	private Date endDate;

	public TblUserModules() {
	}

	public TblUserModules(TblUsers tblUsers, TblModules tblModules,
			Date startDate, Date endDate) {
		this.tblUsers = tblUsers;
		this.tblModules = tblModules;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_module_id", unique = true, nullable = false)
	public Integer getUserModuleId() {
		return this.userModuleId;
	}

	public void setUserModuleId(Integer userModuleId) {
		this.userModuleId = userModuleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public TblUsers getTblUsers() {
		return this.tblUsers;
	}

	public void setTblUsers(TblUsers tblUsers) {
		this.tblUsers = tblUsers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module_id")
	public TblModules getTblModules() {
		return this.tblModules;
	}

	public void setTblModules(TblModules tblModules) {
		this.tblModules = tblModules;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
