package com.heathbot.beans;
// Generated Jan 18, 2018 5:18:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblUserType generated by hbm2java
 */
@Entity
@Table(name = "tbl_user_type", catalog = "healthbot")
public class TblUserType implements java.io.Serializable {

	private Integer userTypeId;
	private String userTypeName;
	private Set<TblUsers> tblUserses = new HashSet<TblUsers>(0);

	public TblUserType() {
	}

	public TblUserType(String userTypeName, Set tblUserses) {
		this.userTypeName = userTypeName;
		this.tblUserses = tblUserses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_type_id", unique = true, nullable = false)
	public Integer getUserTypeId() {
		return this.userTypeId;
	}

	public void setUserTypeId(Integer userTypeId) {
		this.userTypeId = userTypeId;
	}

	@Column(name = "user_type_name")
	public String getUserTypeName() {
		return this.userTypeName;
	}

	public void setUserTypeName(String userTypeName) {
		this.userTypeName = userTypeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblUserType")
	public Set<TblUsers> getTblUserses() {
		return this.tblUserses;
	}

	public void setTblUserses(Set<TblUsers> tblUserses) {
		this.tblUserses = tblUserses;
	}

}
